name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate github profile summary cards
    steps:
      - uses: actions/checkout@v3

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Patrick7241
